export const FETCH_REPO_LIST_LOADING = 'FETCH_REPO_LIST_LOADING';
export const FETCH_REPO_LIST_DONE = 'FETCH_REPO_LIST_DONE';
export const FETCH_REPO_LIST_ERROR = 'FETCH_REPO_LIST_ERROR';

export const SEARCH_REPO_LIST_LOADING = 'SEARCH_REPO_LIST_LOADING';
export const SEARCH_REPO_LIST_DONE = 'SEARCH_REPO_LIST_DONE';
export const SEARCH_REPO_LIST_ERROR = 'SEARCH_REPO_LIST_ERROR';
